const COUNTRY_BY_ID = {
  ailefroide: "France",
  "bow-valley": "Canada",
  bugaboos: "Canada",
  ceuse: "France",
  chamonix: "France",
  "costa-blanca": "Spain",
  dolomites: "Italy",
  "el-potrero-chico": "Mexico",
  "el-salto": "Mexico",
  "finale-ligure": "Italy",
  frankenjura: "Germany",
  "hatun-machay": "Peru",
  kalymnos: "Greece",
  lofoten: "Norway",
  "mineral-del-chico": "Mexico",
  paklenica: "Croatia",
  "pena-de-bernal": "Mexico",
  siurana: "Spain",
  "skaha-bluffs": "Canada",
  squamish: "Canada",
  "todra-gorge": "Morocco",
  "valle-dellorco": "Italy",
  "verdon-gorge": "France",
  arco: "Italy",
  tafraoute: "Morocco",
  margalef: "Spain",
  leonidio: "Greece",
  "mount-arapiles": "Australia",
  liming: "China",
  tsaranoro: "Madagascar",
  "blue-mountains-au": "Australia",
  "waterval-boven": "South Africa",
  nowra: "Australia",
  "frog-buttress": "Australia",
  ogawayama: "Japan",
  "wadi-rum": "Jordan",
  albarracin: "Spain",
  rodellar: "Spain",
  alcaniz: "Spain",
  quiros: "Spain",
  fontainebleau: "France",
  briancon: "France",
  "les-calanques": "France",
  buoux: "France",
  tarn: "France",
  cadarese: "Italy",
  ogliastra: "Italy",
  "val-di-mello": "Italy",
  meteora: "Greece",
  "athens-crags": "Greece",
  lagada: "Greece",
  bohuslan: "Sweden",
  skien: "Norway",
  vingsand: "Norway",
  aland: "Finland",
  "peak-district": "United Kingdom",
  taghia: "Morocco",
  osp: "Slovenia",
  omis: "Croatia",
  "magic-wood": "Switzerland",
  geyikbayiri: "Türkiye",
  aladaglar: "Türkiye",
  quetzaltenango: "Guatemala",
  "cerro-quemado": "Guatemala",
  itatim: "Brazil",
  "el-chonta": "Peru",
  yangshuo: "China",
  palchan: "India",
  aleo: "India",
  "chichoga-road": "India",
  "solang-valley": "India",
  mizugaki: "Japan",
  rocklands: "South Africa",
  "djebel-zaghouan": "Tunisia",
  "djebel-ressas": "Tunisia",
  "oman-climbing": "Oman",
  grampians: "Australia",
  wanaka: "New Zealand",
  "the-remarkables": "New Zealand",
  "castle-hill": "New Zealand",
  flatanger: "Norway",
  "piedra-parada": "Argentina",
  "serra-do-cipo": "Brazil",
  "valle-de-los-condores": "Argentina",
  "railay-tonsai": "Thailand",
  longdong: "Taiwan",
  "paynes-ford": "New Zealand",
  "rocha-da-pena": "Portugal",
  corsica: "France",
  "valle-cochamo": "Chile",
  frey: "Argentina",
  "los-arenales": "Argentina",
  suesca: "Colombia",
  "chalten-massif": "Argentina",
  "banff-national-park": "Canada",
  riglos: "Spain",
  "la-pedriza": "Spain",
  cresciano: "Switzerland",
  chironico: "Switzerland",
  varazze: "Italy",
  hampi: "India",
  gastlosen: "Switzerland",
  wendenstocke: "Switzerland",
  "eldorado-grimsel": "Switzerland",
  salbitschijen: "Switzerland",
  lehn: "Switzerland",
};

export function destinationLocation(destination) {
  const region = String(destination?.region || "").trim();
  if (region && region.toLowerCase() !== "international") return region;
  return COUNTRY_BY_ID[destination?.id] || region || "Location unavailable";
}
