// Campmate verdicts, not guidebook copy. Keep every line punchy and under 25 words.
export const DESTINATION_TLDRS = {
  ailefroide: "Alpine granite buffet; sport climbers accidentally become mountaineers here.",
  "bishop-area": "World-class everything, desert dust in absolutely everything.",
  "black-canyon-gunnison": "Huge, serious, confusing—and the walk out hates you too.",
  "bow-valley": "Endless limestone, ridiculous scenery, Canadian weather doing improv.",
  bugaboos: "Perfect alpine granite guarded by glaciers and deeply unstable weather.",
  ceuse: "Perfect limestone, savage hike. Your calves pay admission.",
  chamonix: "Cable-car alpinism, legendary granite, pastries priced like cams.",
  "city-of-rocks-id": "Granite playground, great moderates, suspiciously wholesome camping.",
  "cochise-stronghold": "Remote granite, spicy runouts, bolts visible only through faith.",
  "costa-blanca": "Sunny limestone and sea views; lunch will derail your training plan.",
  "devils-tower": "Splitter columns, sustained jamming, tourists judging from below.",
  dolomites: "Giant limestone, tiny gear, huts serving dinner above your pay grade.",
  "el-potrero-chico": "Casual access to absurdly long bolted routes. Efficiency eventually required.",
  "el-salto": "Steep tufas, savage pump, one more hang before the send.",
  "eldorado-canyon": "Famous sandstone, baffling route-finding, 5.8s with résumés.",
  "finale-ligure": "Endless limestone, polished classics, pizza-powered recovery.",
  frankenjura: "Short routes, tiny pockets, enormous forearms, excellent beer.",
  "hatun-machay": "Wild volcanic sport climbing where the altitude is the first crux.",
  "horse-pens-40": "Perfect slopers and topouts designed by a vindictive genius.",
  "hueco-tanks": "Sacred bouldering, strict access, world-class sideways humiliation.",
  "indian-creek": "Perfect splitters in every size. Every size hurts.",
  "joshua-tree": "Weird granite, old-school grades, descents occasionally harder than climbing.",
  kalymnos: "Tufas, scooters, sea views, and absolutely fake rest days.",
  lofoten: "Arctic granite perfection; midnight sun, weather with commitment issues.",
  "maple-canyon": "Steep cobbles glued together by geology and poor judgment.",
  "mineral-del-chico": "Cool volcanic towers, big variety, beta occasionally lost in translation.",
  "mount-lemmon": "Drive uphill until the temperature stops trying to kill you.",
  "new-river-gorge": "Bullet sandstone, endless classics, stairs for emotional damage.",
  paklenica: "Roadside limestone that casually becomes a giant multipitch wall.",
  "pena-de-bernal": "Big volcanic summit adventure; easy route, confusing route-finding.",
  "red-river-gorge": "Steep pockets, soft catches, zero functional forearms by dinner.",
  "red-rock-canyon": "World-class sandstone beside Vegas; parking is pitch one.",
  rifle: "Polished limestone where strong climbers go to feel aggressively average.",
  "rmnp-rock": "Superb alpine granite; thunder handles the closing announcement.",
  rumney: "New England sport heaven; bugs and schist keep egos calibrated.",
  "sinks-canyon": "Pocketed dolomite, year-round options, wind stealing your chalk.",
  siurana: "Perfect edges, tiny feet, one-more-go syndrome with village views.",
  "skaha-bluffs": "Friendly gneiss cragging conveniently paired with wine country.",
  "smith-rock": "Historic tuff, iconic routes, mandatory uphill walk of shame.",
  squamish: "World-class granite when dry. Everyone becomes a meteorologist.",
  tahquitz: "Historic granite multipitch; the grades remember the 1950s.",
  "ten-sleep-canyon": "Pocketed dolomite paradise; your warm-up is now a project.",
  "the-needles-ca": "California’s best granite, inconveniently hidden from casual people.",
  "todra-gorge": "Tall Moroccan limestone with tourists wandering through your belay.",
  "tuolumne-meadows": "Glorious high-country granite; the 5.7 slab is absolutely not kidding.",
  "valle-dellorco": "Little Yosemite, better espresso, same crack-climbing ego check.",
  "verdon-gorge": "Rappel into enormous limestone, then discover retreat was theoretical.",
  "wild-iris": "Beautiful dolomite pockets with zero sympathy for weak fingers.",
  "yosemite-valley": "Best granite on earth, worst place to quietly mention the Nose.",
  zion: "Huge sandstone, serious routes, sand entering every known pocket.",
  arco: "Infinite limestone beside Lake Garda; gelato counts as recovery.",
  tafraoute: "Remote desert granite, huge freedom, beta mostly vibes.",
  taghia: "Massive remote limestone for people whose systems actually work.",
  margalef: "Pocketed conglomerate and enough monos to fund hand surgeons.",
  leonidio: "Tufa heaven, winter sun, dinner destroying tomorrow’s early start.",
  "mount-arapiles": "Trad university with world-class rock and unsolicited campground beta.",
  liming: "Splitter sandstone from fingers to full-body regret.",
  tsaranoro: "Madagascar big walls: huge granite, huge runouts, tiny rescue options.",
  "blue-mountains-au": "Endless sandstone gorges; somehow every approach contains stairs.",
  "waterval-boven": "Bullet quartzite, steep sport, forearms formally resigning by day three.",
  nowra: "Powerful sandstone caves exposing everyone who skipped pull-ups.",
  "frog-buttress": "Perfect rhyolite cracks and Australian grades with opinions.",
  ogawayama: "Japanese granite summer camp; excellent climbing, rapidly disappearing skin.",
  "wadi-rum": "Cinematic sandstone towers, experimental protection, adventurous descents.",
  albarracin: "Orange sandstone, savage mantels, medieval-town rest days.",
  rodellar: "Endless tufas for people who consider forty moves a warm-up.",
  alcaniz: "Low-key Aragon climbing without the celebrity-crag circus.",
  quiros: "Cool green limestone, quiet crags, weather using every icon.",
  fontainebleau: "Perfect sandstone and ten thousand ways to fail waist-high.",
  briancon: "Every rock type, every climbing style, zero easy sector decisions.",
  "les-calanques": "White limestone over blue water; French parking is the crux.",
  buoux: "Historic pockets, polished feet, dead climbers still sandbagging you.",
  tarn: "Long limestone pump-fests where an 80-meter rope feels optimistic.",
  cadarese: "European gneiss cracks so good even crack snobs stop complaining.",
  ogliastra: "Wild Sardinian limestone; sea stacks, sunshine, catastrophic trip extension.",
  "val-di-mello": "Italian granite slabs asking whether your feet contribute anything.",
  meteora: "Monastery-topped towers climbed on cobbles, faith, and spaced protection.",
  "athens-crags": "Quick limestone sessions before an aggressively long Greek dinner.",
  lagada: "Quiet Peloponnese limestone without the famous-crag queue.",
  bohuslan: "Immaculate Swedish granite cracks; no bolts, no nonsense.",
  skien: "Solid Norwegian cragging where weather remains the main character.",
  vingsand: "Quiet coastal gneiss, sea views, waterproof personality required.",
  aland: "Baltic granite slabs, peaceful islands, highly organized mosquitoes.",
  "peak-district": "Tiny cliffs, enormous history, six-meter routes that haunt careers.",
  osp: "Steep Slovenian limestone where your warm-up already looks hard.",
  omis: "Croatian limestone beside the sea; summer shade is advanced beta.",
  "magic-wood": "Hard gneiss in a dark forest; skin and confidence vanish together.",
  geyikbayiri: "Tufa-filled Turkish limestone with winter sun and heroic beach muscles.",
  aladaglar: "Huge Taurus limestone, thin beta, absolutely no app-based rescue plan.",
  "linville-gorge": "Wild quartzite where approaches and descents also demand a rack.",
  shawangunks: "Friendly grades, enormous roofs, rope management publicly audited.",
  "stone-mountain-nc": "Holdless granite slabs with bolts in a neighboring ZIP code.",
  whitesides: "Huge, serious, runout—casual sightseeing firmly unavailable.",
  "laurel-knob": "Remote granite, long runouts, carry everything, trust nothing.",
  "panthertown-valley": "Backcountry granite with peaceful climbing and chaotic navigation.",
  "index-wa": "Incredible granite, savage grades, probably wet.",
  "joes-valley": "Perfect roadside sandstone, easy landings, impossible departure date.",
  moab: "Iconic desert towers; summit photos hide several hours of terror.",
  "suicide-rock": "Steep SoCal granite; the approach removes casual enthusiasm.",
  "shelf-road": "Pocketed limestone, easy camping, cactus enforcing rope discipline.",
  "the-hulk-sierra": "Incredible granite, windy af.",
  lander: "A climbing town surrounded by pockets, friendly dirtbags, and wind.",
  "washington-pass": "Roadside alpine granite; conveniently located thunderstorms.",
  "grand-tetons": "Iconic alpine climbing with approaches that fact-check your fitness.",
  "high-sierra-whitney": "Perfect high-altitude granite; oxygen sold separately.",
  "sequoia-np": "Remote Sierra granite where forgotten gear becomes a life lesson.",
  quetzaltenango: "Developing highland crags; local beta beats glossy expectations.",
  "cerro-quemado": "Volcanic climbing where loose-rock awareness never clocks out.",
  itatim: "Bahia granite giants under sun that demands alpine starts.",
  "el-chonta": "High-altitude limestone; fingers ready, lungs filing paperwork.",
  yangshuo: "Surreal karst climbing, tropical humidity, rest-day eating Olympics.",
  palchan: "Developing Himalayan granite where the background does most of the flexing.",
  aleo: "Small Manali crags, evolving beta, zero artisanal signage.",
  "chichoga-road": "Roadside granite, local adventure, occasionally more road than climbing.",
  "solang-valley": "Scenic Himalayan cragging for people comfortable with incomplete information.",
  mizugaki: "Pristine Japanese granite quietly sanding off every fingertip.",
  rocklands: "World-class orange sandstone plus permits, driving, and skin math.",
  "djebel-zaghouan": "Big Tunisian limestone; bring local beta and bolt skepticism.",
  "djebel-ressas": "Limestone above Tunis where winging it becomes multipitch strategy.",
  grampians: "World-class sandstone with access rules that deserve actual reading.",
  wanaka: "Good schist, huge views, cafés aggressively competing with climbing.",
  "the-remarkables": "Alpine rock above Queenstown; escape tourists, meet wind.",
  "castle-hill": "Beautiful limestone eggs with no holds where humans want them.",
  adirondacks: "Six million acres of granite, blackflies, and vague meeting points.",
  sedona: "Gorgeous soft sandstone with gear placements based partly on hope.",
  "elephants-perch": "Boat, hike, giant granite, no Uber home.",
  "the-fins": "Remote Idaho limestone with perfect pockets and zero forgotten-gear forgiveness.",
  "little-river-canyon": "Steep Alabama sandstone; hard climbing, chalk-soup humidity.",
  "rockford-park": "Legit Delaware bouldering with a water tower for alpine ambiance.",
  oahu: "Better climbing than expected; still remember you flew to Hawaii.",
  kauai: "Beach bouldering good, inland rock actively plotting against you.",
  "tubbs-hill": "Downtown lakefront bouldering with swimming as the sensible option.",
  "pictured-rocks": "Shaded Iowa sport climbing; polished, social, seepy after rain.",
  "backbone-state-park": "Iowa bouldering hidden behind weaponized summer vegetation.",
  "the-lost-city-of-critzer": "Kansas bouldering with a name far taller than the cliffs.",
  "st-philippine-duchesne-park": "Compact Kansas limestone proving flat states still have topouts.",
  "foxtown-boulders": "Wild Kentucky sandstone; ‘next boulder’ is never nearby.",
  "acadia-national-park": "Sea-cliff granite, ocean views, tides trying to steal your rack.",
  "harpers-ferry": "Three states, two rivers, quartzite, constant train-powered screams.",
  "northwest-branch": "D.C.-area bouldering: dense problems, short cliffs, swampy summer friction.",
  "north-shore": "Endless Massachusetts boulders; parking beta is the real guidebook.",
  tishomingo: "Mississippi sandstone, humid friction, mountains not actually required.",
  pawtuckaway: "Granite maze, classic boulders, bugs with excellent navigation.",
  "albuquerque-area": "Every rock, every style, every crag apparently somewhere else.",
  "jemez-mountains-and-jemez-valley": "Volcanic variety so scattered that choosing a crag is crux one.",
  "lincoln-woods": "A thousand granite problems and five-minute walks that absolutely aren’t.",
  "beach-pond": "Quiet granite bouldering; the crash pad is the only beach.",
  "big-rock-mountain": "South Carolina granite buffet; everyone can suffer their preferred way.",
  "table-rock-state-park": "Serious granite slabs; picnic-area expectations will be punished.",
  "the-needles-of-rushmore": "Granite spires, huge runouts, scenic panic attacks.",
  "spearfish-canyon": "A thousand limestone routes; ‘one more’ becomes regional travel.",
  "bubbs-creek-wall": "Remote nineteen-pitch granite; forgetting the topo creates a new route.",
  "patterson-left": "Rappel into giant granite and immediately reconsider your systems.",
  "trout-creek": "Perfect basalt splitters, brutal stemming, eagles own the summer.",
  "the-grail": "Shady limestone, long 5.12s, warm-ups ending in negotiations.",
  leavenworth: "Granite everything plus Bavarian cosplay and enormous sausages.",
  "little-cottonwood-canyon": "World-class granite and bouldering; parking remains undefeated.",
  "devils-lake": "Slick quartzite, tiny feet, bolts politely not invited.",
  vedauwoo: "Windy offwidth hell. Beautiful, if you own knee pads.",
  "horseshoe-canyon-ranch": "Friendly sandstone, easy logistics, actual horses judging your clipstick.",
  "obed-clear-creek": "Steep Tennessee sandstone; summer includes complimentary sauna.",
  "american-fork-canyon": "Pocketed limestone and fingers requesting union representation.",
  "stone-fort": "World-class bouldering beside a golf course. Sure, why not.",
  "boulder-canyon": "Roadside granite; parking may be today’s boldest lead.",
  "mount-charleston": "Hard limestone above Vegas, mercifully below desert temperature.",
  "seneca-rocks": "Exposed quartzite fin; friendly grades, unfriendly route-finding.",
  "donner-summit": "Excellent roadside granite if snow and Californians leave space.",
  "lovers-leap": "Perfect moderate multipitch, positive dikes, predictable queue.",
  "clear-creek-canyon": "Thousands of roadside bolts with premium highway ambience.",
  flatirons: "Giant sandstone slabs; climb before breakfast, get lost before lunch.",
  "big-cottonwood-canyon": "Quartzite variety near town; watershed rules kill van-life improv.",
  rocktown: "Sculpted sandstone and topouts professionally removing dignity.",
  "tennessee-wall": "Elite sandstone trad above the river; check hunting season first.",
  "jackson-falls": "Pocketed Illinois sandstone; Midwest nice, grades not necessarily.",
  "holy-boulders": "Excellent climber-owned sandstone supporting future public humiliation.",
  "moes-valley": "Perfect winter sandstone; wet rock and fake topout beta prohibited.",
  "saxon-switzerland": "Sandstone towers, textile gear, no chalk—your rack is contraband.",
  montserrat: "Endless cobble towers; finding the descent remains tomorrow’s problem.",
  "la-pedriza": "Six thousand granite choices, mostly involving friction and indecision.",
  zillertal: "Alpine granite buffet with toll roads and weather paperwork.",
  chironico: "Two thousand gneiss problems, uphill pads, rude sit-starts.",
  cresciano: "Historic gneiss, elite testpieces, confidence left in the village.",
  "brione-verzasca": "Photoshopped-looking gneiss with parking rules and seasonal meadow drama.",
  mallorca: "Limestone paradise; calm seas and trustworthy bolts not guaranteed.",
  "el-chorro": "Andalusian limestone, complex rules, railway definitely not an approach.",
  chulilla: "Endless endurance routes for climbers emotionally attached to 80-meter ropes.",
  "san-vito-lo-capo": "Sicilian limestone and seafood; saltwater does terrible bolt maintenance.",
  gastlosen: "Jagged Swiss limestone; alpine weather retains veto power.",
  varazze: "Hard Italian bouldering fueled by winter friction and espresso delusion.",
  riglos: "Giant cobble towers where every loose-looking hold triggers philosophy.",
  "railay-tonsai": "Tufas, beaches, tropical heat, sand permanently inside your rope.",
  "thakhek-pha-tam-kam": "Lao tufa paradise; winter good, late-season air deeply chewable.",
  "serra-do-cipo": "Brazilian limestone where cruxes apparently skipped the warm-up.",
  frey: "Golden granite spires and one cloud rewriting your entire day.",
  "valle-cochamo": "Chilean Yosemite without roads, signal, or convenient forgotten gear.",
  "chalten-massif": "Iconic Patagonian granite; weather windows measured in emotional trauma.",
  hampi: "Granite boulders among ruins; climb respectfully, archaeology is not a hold.",
  "darran-mountains": "Serious Fiordland rock; check the forecast, then laugh sadly.",
  "valle-de-los-condores": "Remote basalt perfection; modern bolts, medieval logistics.",
  "los-arenales": "High-Andes granite wearing a casual-cragging disguise.",
  "la-huasteca": "Huge limestone beside Monterrey; summer is a toaster.",
  suesca: "Historic Colombian sandstone with trains providing unsolicited power screams.",
  "piedra-parada": "Patagonian tuff, savage wind, winter climbing legally canceled.",
};
